Another changed to define a success

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,6 +1,3 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-
 name: Node.js CI
 
 on:
@@ -26,4 +23,15 @@ jobs:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
     - run: npm i
-    - run: npm run start
+    - name: Start the application
+      run: npm run start > app.log 2>&1
+      continue-on-error: true
+    - name: Check for successful start
+      run: |
+        if grep -q "Running at Port 4000" app.log; then
+          echo "Success"
+          exit 0
+        else
+          echo "Failed"
+          exit 1
+        fi
